# General Site Settings

title: Kross
logo: 
author: themefisher
description: this is meta description
email: steve.fruits@email.com
phone: +880 2544 658 256
address: 125/A, CA Commercial Area, California, USA
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: About, link: 'aboutme'}
- {name: Portfolio, link: 'works'}
