#-------------------------------
# General Site Settings

title: Matthieu Alessi
logo: logo.png


menu:
- {name: About, link: '/about'}
- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: Shortname # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Matthieu Alessi
  hero-subtitle: Graphic Design | Interface Design | Illustration


#-------------------------------
# About (Section and Page)

# About Section
blurb: "Hello & Welcome to my portfolio, my work that is presented here is focused on visual design and user interfaces. I aim to use complementary skills in my own practice. "

blurb-btn-link: '/about'
blurb-btn-name: know more



# About Page




#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Graphic Design, color: '#fdb157', value: '90%'}
- {name: UI Design, color: '#9473e6', value: '60%'}
- {name: UX Design, color: '#bdecf6', value: '80%'}
- {name: Illustration, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

experience-title: Skills
experience:
- {name: Adobe Suite, icon: 'icon-3.png', date: '⚪⚪⚪⚪⚪', organization: 'PS, AI, IND, AE'}
- {name: Drawing Skills, icon: 'icon-2.png', date: '⚪⚪⚪⚪', organization: 'Traditional & Digital'}
- {name: HTML/CSS, icon: 'icon-1.png', date: '⚪⚪', organization: 'Beginner'}
- {name: English, icon: 'icon-2.png', date: '⚪⚪⚪⚪', organization: 'C1 - (955) TOEIC'}


#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: Graphic Design,
    icon: ti-vector,
    description: 'Graphic design is present in most of my realisations, I apply Graphic Design principles on a daily basis and aim to link them to other visual fields.',
    active: # Add true to select section
  }
- {
    name: UX/UI Design,
    icon: ti-panel,
    description: 'I have more experience on the UI side of interfaces, I aim to know more about how people operate and be able to optimize those experiences.',
    active: true # Add true to select section
  }
- {
    name: Art & Illustration,
    icon: ti-palette,
    description: 'Illustration is a skill I have been working on for a long time, from paper to tablet, allowing me to create visual elements or personal pieces.',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section

portfolio-btn-link: '/portfolio'
portfolio-btn-name: see more

portfolio-home-items:
  - image : "projects/images/ftc-interfaces/item-2.jpg"
    title : "FTC Interfaces"
    tags: "Interface Design"
    url: "projects/FTC-interfaces"
    
  - image : "projects/images/radiant/item-1.jpg"
    title : "Radiant Cafe"
    tags: "Branding - UI Design"
    url: "projects/radiant"
    portfolio-type:
      - type: "illustration"
      - type: "graphic design"
      - type: "interface"
    
  - image : "projects/images/aeternam/item-1.jpg"
    title : "Aeternam"
    tags: "Branding - Illustration"
    url: "projects/aeternam"
    
  - image : "projects/images/steloi/item-1.jpg"
    title : "Saint-Éloi School"
    tags: "Graphic Design - Branding"
    url: "projects/st-eloi-school"
   
  - image : "projects/images/morgentime/item-1.jpg"
    title : "Morgentime"
    tags: "Interface Design"
    url: "projects/morgentime"
   

# Portfolio Page
portfolio-label:
- {
    title : "Interface Design",
    type : "interface"
    
  }
- {
    title : "Graphic Design",
    type : "graphic design"
  }
- {
    title : "Illustration",
    type : "illustration"
  }

portfolio-items:

  - image : "projects/images/ftc-interfaces/item-1.jpg"
    title : "FTC Interfaces"
    tags: "Interface Design"
    url: "projects/FTC-interfaces"
    portfolio-type:
      - type: "interface"
      
  - image : "projects/images/illustrations/item-1.jpg"
    title : "Illustrations Digitales"
    tags: "Illustration"
    url: "projects/illustrations"
    portfolio-type:
      - type: "illustration" 
      
  - image : "projects/images/radiant/item-1.jpg"
    title : "Radiant Cafe"
    tags: "Branding - UI Design"
    url: "projects/radiant"
    portfolio-type:
      - type: "illustration"
      - type: "graphic design"
      - type: "interface"
 
  - image : "projects/images/morgentime/item-1.jpg"
    title : "Morgentime"
    tags: "Interface Design"
    url: "projects/morgentime"
    portfolio-type:
      - type: "interface"
      
  - image : "projects/images/spartan-race-logo/item-1.jpg"
    title : "Spartan Race Logo Redesign"
    tags: "Graphic Design - Logo Design"
    url: "projects/spartan-race-logo"
    portfolio-type:
      - type: "graphic design"
      

  - image : "projects/images/musical-player/item-1.jpg"
    title : "Music Player UI"
    tags: "UI Design"
    url: "projects/music-player-UI"
    portfolio-type:
      - type: "interface"
  
  - image : "projects/images/tiles/item-1.jpg"
    title : "Tiles Mailbox"
    tags: "UI Design"
    url: "projects/tiles"
    portfolio-type:
      - type: "interface"
  
  - image : "projects/images/aeternam/item-1.jpg"
    title : "Aeternam"
    tags: "Branding - Illustration"
    url: "projects/aeternam"
    portfolio-type:
      - type: "graphic design"
      - type: "illustration"
      
  - image : "projects/images/wirecast/item-1.jpg"
    title : "Wirecast"
    tags: "Interface Design"
    url: "projects/wirecast"
    portfolio-type:
      - type: "interface"
      
  - image : "projects/images/steloi/item-1.jpg"
    title : "Saint-Éloi School"
    tags: "Graphic Design - Branding"
    url: "projects/st-eloi-school"
    portfolio-type:
      - type: "graphic design"
     


#-------------------------------
# Contact Section

contact-title: Feel free to contact me if you need anything.
contact-email: matthieu.alessi@gmail.com
